name: Perforce
description: Checks out a perforce repository instead of git.
author: https://github.com/ca-johnson
configuration:
  properties:
    p4port:
      type: string
    p4user:
      type: string
    p4tickets:
      type: string
    p4trust:
      type: string  
    view:
      type: string
    stream:
      type: string
    sync:
      type: string
    parallel:
      type: string
    client_opts:
      type: string
    backup_changelists:
      type: bool
