---
name: Perforce
description: Checks out a perforce repository instead of git.
author: https://github.com/inflexiongames
requirements:
  - p4
configuration:
  properties:
    client_options:
      type: string
    client_type:
      type: string
    p4port:
      type: string
    p4tickets:
      type: string
    p4trust:
      type: string
    p4user:
      type: string
    parallel:
      type: string
    share_workspace:
      type: boolean
    stream_switching:
      type: boolean
    sync:
      type: array
    fingerprint:
      type: string
    view:
      type: string
