name: Perforce
description: Checks out a perforce repository instead of git.
author: https://github.com/ca-johnson
configuration:
  properties:
    backup_changelists:
      type: bool
    client_options:
      type: string
    client_type:
      type: string
    p4port:
      type: string
    p4tickets:
      type: string
    p4trust:
      type: string
    p4user:
      type: string
    parallel:
      type: string
    share_workspace:
      type: bool
    stream:
      type: string
    stream_switching:
      type: bool
    sync:
      type: array
    trusted_fingerprints:
      type: array
    view:
      type: string
