steps:
  - label: "Test"
    command: echo "Hello World"
    plugins:
      - ./.buildkite/plugins/perforce:
          p4port: localhost:1666
          p4user: banana
          view: //depot/... ...
          root: p4_workspace
          parallel: 2