#!/bin/bash
set -euo pipefail


# Before this ever runs, you need:
# 'p4' in PATH
# trust for p4 server
# 

echo "~~~ Perforce Checkout"
export P4PORT="${BUILDKITE_PLUGIN_PERFORCE_P4PORT:-$P4PORT}"
export P4USER="${BUILDKITE_PLUGIN_PERFORCE_P4USER:-$P4USER}"

${BUILDKITE_PLUGIN_PERFORCE_STREAM}
${BUILDKITE_PLUGIN_PERFORCE_VIEW}

ROOT=${BUILDKITE_PLUGIN_PERFORCE_ROOT:-$BUILDKITE_BUILD_CHECKOUT_PATH}

python ./python/checkout.py --root "${ROOT}" 
exit 0


# Override p4 env vars with plugin configuration

# Considerations:
# Workspace root should be something near $BUILDKITE_BUILD_CHECKOUT_PATH
# Clients may or may not already exist
# Clients may have a different workspace mapping/stream since last time
p4 info

# For now, just create default client. Named with machine name.
p4 client -o
p4 client -o | p4 client -i 

# p4 sync //depot/file.txt
p4 sync //nwx/dev/UE4/ci/setup-and-build.ps1

# NWX perforce fingerprint (for p4 trust -i):
# 35.203.30.49:1666 94:48:85:E4:0C:A5:64:ED:32:CB:2B:4C:55:CD:49:97:30:8D:D4:9F

# To iterate:
# ~/platform> bk local run .buildkite/perforce-test.steps.yaml