#!/bin/bash
set -euo pipefail

plugin_root="${BASH_SOURCE%/*}/.."

venv_dir="${BUILDKITE_BUILD_CHECKOUT_PATH}/../.perforce-plugin-venv"

platform=$(python -c "import platform; print(platform.system())")
if [[ "${platform}" == "Windows" ]]; then
    venv_bin="${venv_dir}/Scripts"
else
    venv_bin="${venv_dir}/bin"
fi


"${venv_bin}/python" "${plugin_root}/python/pre-exit.py"
